version: '3'

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
            - "./etc/db/dumps:/var/tmp/dumps"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${PORT_DATABASE:-3306}:3306

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - TIMEZONE=${TIMEZONE}
                - INSTALL_SYMFONYCLI=${INSTALL_SYMFONYCLI}    
                - INSTALL_NODE=${INSTALL_NODE}    
                - NODE_VERSION=${NODE_VERSION}
                - INSTALL_YARN=${INSTALL_YARN}
        volumes:
            - ${APP_PATH}:/var/www/
        ports:
            - ${PORT_PHPDEV:-9000}:9000

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ${APP_PATH}:/var/www/
        ports:
            - ${PORT_HTTP:-80}:80
            - ${PORT_HTTPS:-443}:443

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - ${PORT_PHPMYADMIN:-8080}:80
        volumes:
            - /sessions
        links:
            - db
volumes:
    db_app:
