version: '3'

services:
    db:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${PORT_DATABASE:-3306}:3306
        networks:
            - zikula
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./../core/:/var/www/zikula/
        ports:
            - ${PORT_PHPDEV:-9000}:9000
        networks:
            - zikula
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./../core/:/var/www/zikula/
        ports:
            - ${PORT_HTTP:-80}:80
            - ${PORT_HTTPS:-443}:443
        networks:
#            - zikula
            zikula:
                aliases:
                    - zikula.localhost
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        ports:
            - ${PORT_PHPMYADMIN:-8080}:80
        volumes:
            - /sessions
        links:
            - db
        networks:
            - zikula
volumes:
    db_app:

networks:
    zikula:
